### ISSUE TITLE
Subnet domain export vs import

### ISSUE THREAD

**Issue by jovandeginste** [adfinis-sygroup/foreman-yml#33]
Exporting subnets has the following structure:

```yaml
subnet:
- name: xyz
  otherkeys: othervalues
  domain:
  - mydomain.example.org
```

The importer however expects this format:

```yaml
subnet:
- name: xyz
  otherkeys: othervalues
  domain:
  - name: mydomain.example.org
```
